apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: backend-app
spec:
  replicas: {{ .Values.replicas.backend | quote }}
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend
        envFrom:
        - configMapRef:
            name: backend-app-config
        image: {{ .Values.images.backend | quote }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 2
          tcpSocket:
            port: 3000
          timeoutSeconds: 3
      restartPolicy: Always
